### ISSUE TITLE
Does not work properly on emacs 27

### ISSUE THREAD

**Issue by cnsunyour** [hadronzoo/theme-changer#14]
I really like this package. I have been using theme-changer on emacs 26 to switch themes automatically. 

But after upgrading to emacs 27, the theme cannot be switched automatically, and the theme can be set correctly only at startup.

**Comment by tshu-w** [comment]
same issue here.

**Comment by isfttr** [comment]
Same issue.

**Comment by tshu-w** [comment]
I'm using emacs-plus on mac now, which has a patch that provide a system appearance change hook.

**Comment by cnsunyour** [comment]
I submitted a PR to  fixed this issue.  https://github.com/hadronzoo/theme-changer/pull/15
