### ISSUE TITLE
Offer to Maintain

### ISSUE THREAD

**Issue by swflint** [hadronzoo/theme-changer#19]
You've mentioned that you're looking for a maintainer.  I find this package to be immensely useful, and would like to see it continued to be worked on and updated.  I'm willing to take on the task if you're still looking for someone.

**Comment by hadronzoo** [comment]
Thank you. I'm happy for it to be maintained by someone who finds it useful.

**Comment by swflint** [comment]
Here's hoping it works out well for people!

**Comment by pataquets** [comment]
@swflint Are you still maintaining the package? The readme still has the "maintainer wanted" notice, but I can see a `new-maintainer` branch, which I guess it would be desirable to merge into `master`.

**Comment by swflint** [comment]
I mean, I'm still willing to take it on, and I *think* I could effectively take over.  However, I'd prefer to get @hadronzoo's formal okay to do it

**Comment by hadronzoo** [comment]
Yes, help maintaining would be immensely appreciated. I do not currently have time to do so.

**Comment by swflint** [comment]
Awesome!  I'm still very much willing!

**Comment by hadronzoo** [comment]
merged. thank you @swflint!
