### ISSUE TITLE
It broke suddenly after updating few packages

### ISSUE THREAD

**Issue by amritoit** [hadronzoo/theme-changer#24]
Can you help to fix this ? 

`_Debugger entered--Lisp error: (error "Too many arguments")
  (defvar theme-changer-post-change-hook nil ("c:/Users/abc/AppData/Roaming/.emacs.d/elpa/th..." . 1171) :type 'hook :group 'theme-changer)
  require(theme-changer)
  load-with-code-conversion("c:/Users/abc/AppData/Roaming/.emacs.d/init.el" "c:/Users/abc/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/abc/AppData/Roaming/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0xbd4630b4395cf5c>) #f(compiled-function () #<bytecode -0x1f3c686ddc0da035>) t)
  command-line()
  normal-top-level()_`

**Comment by swflint** [comment]
This is fixed in #22.  Please update again.
