### ISSUE TITLE
Does it even work with Emacs 24?

### ISSUE THREAD

**Issue by kyrylo** [hadronzoo/theme-changer#3]
```
% emacs --version
GNU Emacs 24.3.1
```

I'm an Emacs newbie and I'm having problems with your plugin. I installed it via ELPA, then added this to my `init.el`:

```
(setq calendar-location-name "Dallas, TX") 
(setq calendar-latitude 32.85)
(setq calendar-longitude -96.85)

(change-theme 'adwaita 'wombat)
```

And when I launch Emacs, I get this.

```
Warning (initialization): An error occurred while loading `/home/curacao/.emacs.d/init.el':

Symbol's function definition is void: change-theme

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

This is the backtrace from Emacs launch with `--debug-init` flag.

```
Debugger entered--Lisp error: (void-function change-theme)
  (change-theme (quote adwaita) (quote wombat))
  eval-buffer(#<buffer  *load*> nil "/home/curacao/.emacs.d/init.el" nil t)  ; Reading at buffer position 719
  load-with-code-conversion("/home/curacao/.emacs.d/init.el" "/home/curacao/.emacs.d/init.el" t t)
  load("/home/curacao/.emacs.d/init" t t)
```

Both `M-x load-theme <RET> wombat` and `M-x load-theme <RET> adwaita` work fine.

**Comment by deadghost** [comment]
Also getting `(wrong-type-argument number-or-marker-p nil)` on emacs 24.3.1. I had this working perfectly on my laptop too, unfortunately it died on me and I can't easily check the version.

**Comment by deadghost** [comment]
Resolved my issue. The solar package seems to get my system time/timezone which was out of sync with the location I specified in my config. Changing my timezone in ubuntu resolved it.

**Comment by idoo** [comment]
i use spacemacs with emac-mac
```
  (require 'solar)
  (require 'theme-changer)
  (setq calendar-location-name "st. Petersburg, Russia")
  (setq calendar-latitude 59.53)
  (setq calendar-longitude 30.15)
  (change-theme 'material-light 'material)
```
but get this error in startup
not such file or directory theme-changer

**Comment by idoo** [comment]
@hadronzoo up
please help me :)

**Comment by leongithub** [comment]
(setq calendar-location-name "Dallas, TX") 
(setq calendar-latitude 32.85)
(setq calendar-longitude -96.85)

use your ip on https://db-ip.com/ get your location, latitude and longitude repalce above.

**Comment by AssailantLF** [comment]
I was having this exact issue with this error by calling `change-theme`: `(wrong-type-argument number-or-marker-p nil)`

But after changing my coordinates via https://db-ip.com/ as @leongithub suggested, everything works fine.

So I believe this issue should be closed, as it isn't a bug, and anyone experiencing it has just used incorrect coordinates values.

**Comment by kyrylo** [comment]
I guess this was resolved?

**Comment by hadronzoo** [comment]
Closed based on the previous comment, but please feel free to reopen if this was not accurate.
