### ISSUE TITLE
Wrong type argument: number-or-marker-p on startup, but not always when eval'ed interactively 

### ISSUE THREAD

**Issue by usharf** [hadronzoo/theme-changer#5]
I'm getting this error on startup  (from solar.el it seems): 

```lisp
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  solar-exact-local-noon((10 29 2013))
  solar-sunrise-sunset((10 29 2013))
  sunrise-sunset-times((10 29 2013))
  change-theme(solarized-light zenburn)
  eval-buffer(#<buffer  *load*-516236> nil "/Volumes/Data/uri/.emacs.d/config/_appearance.el" nil t)  ; Reading at buffer position 156
  load-with-code-conversion("/Volumes/Data/uri/.emacs.d/config/_appearance.el" "/Volumes/Data/uri/.emacs.d/config/_appearance.el" nil t)
  require(_appearance)
  eval-buffer(#<buffer  *load*> nil "/Volumes/Data/uri/.emacs.d/init.el" nil t)  ; Reading at buffer position 273
  load-with-code-conversion("/Volumes/Data/uri/.emacs.d/init.el" "/Volumes/Data/uri/.emacs.d/init.el" t t)
  load("/Volumes/Data/uri/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323$
  command-line()
  normal-top-level()
```

I've managed though to eval it once or twice from a buffer, w/o a problem, and it worked fine, so not sure where the problem is.

I've got is setup like this:

```lisp
(setq calendar-location-name "Geneva, Switzerland")
(setq calendar-latitude 46.12)
(setq calendar-longitude 6.9)
...
(require 'theme-changer)
(change-theme 'solarized-light 'zenburn)
```

Though I've tried different combos of themes and locations...

**Comment by peterhadlaw** [comment]
I am having the same issue here. Let me know if there's anyway I can help.

**Comment by usharf** [comment]
Looks like it is related to the value of calendar-latitude/longitude... being either nil or wrong(?). I've added a defadvice to rase-start to prevent it from trying to calculate changes if they are not set, but it still fails with some (maybe incorrect) values.

**Comment by usharf** [comment]
I'm actually seeing it right now, and it is trigged here:

```emacs-lisp 
	   (let ((midnight (/ sunrise 2.0)))
	     (list (cons 'midnight midnight) (cons 'sunrise sunrise)
		   (cons 'midday (+ midnight 12)))))
```
with solar-info ((10.549999999813735 "CEST") nil "13:44")
where sunrise evals to (10.549999999813735 "CEST")
and calendar-longitude 6.1 and calendar-latitude 46.2

**Comment by peterhadlaw** [comment]
@usharf Sorry about the late response. Just wanted to let you know that your change on `rase` fixed my problem. Thank you very much!

**Comment by usharf** [comment]
No problem!
